export const category = [
  'Aksesori Fashion',
  'Aksesori Perhiasan & Produk Turunannya',
  'Koper & Tas',
  'Pakaian & Pakaian Dalam Pria',
  'Busana Muslim',
  'Sepatu',
  'Olahraga & Outdoor',
  'Pakaian & Pakaian Dalam Wanita',
  'Buku, Majalah, & Audio',
  'Komputer & Peralatan Kantor',
  'Peralatan Rumah Tangga',
  'Ponsel & Elektronik',
  'Produk Virtual',
  'Bayi & Ibu Hamil',
  'Kecantikan & Perawatan Pribadi',
  'Makanan & Minuman',
  'Kesehatan',
  'Pakaian Anak',
  'Minuman Keras dan Produk Minuman',
  'Mobil & Sepeda Motor',
  'Barang Koleksi',
  'Furnitur',
  'Dekorasi Rumah',
  'Perlengkapan Rumah',
  'Perlengkapan Dapur',
  'Perlengkapan Hewan Peliharaan',
  'Tekstil & Produk dari Kain',
  'Alat & Perkakas',
  'Mainan & Hobi',
];

export const subCategory = [
  {
    label: 'Aksesoris Pakaian',
    category: 'Aksesori Fashion',
    value: 6.5,
  },
  {
    label: 'Perhiasan & AKsesoris Kostum',
    category: 'Aksesori Fashion',
    value: 6.5,
  },
  {
    label: 'Bahan Pakaian',
    category: 'Aksesori Fashion',
    value: 6.5,
  },
  {
    label: 'Kacamata',
    category: 'Aksesori Fashion',
    value: 6.5,
  },
  {
    label: 'Perhiasan Fashion',
    category: 'Aksesori Fashion',
    value: 6.5,
  },
  {
    label: 'Aksesoris Rambut',
    category: 'Aksesori Fashion',
    value: 6.5,
  },
  {
    label: 'Ekstensi Rambut & Wig',
    category: 'Aksesori Fashion',
    value: 6.5,
  },
  {
    label: 'Logam Berharga & Permata',
    category: 'Aksesori Fashion',
    value: 6.5,
  },
  {
    label: 'Jam Tangan & Aksesoris',
    category: 'Aksesori Fashion',
    value: 6.5,
  },
  {
    label: 'Ambar',
    category: 'Aksesori Perhiasan & Produk Turunannya',
    value: 4,
  },
  {
    label: 'Permata Sintesis',
    category: 'Aksesori Perhiasan & Produk Turunannya',
    value: 4,
  },
  {
    label: 'Berlian',
    category: 'Aksesori Perhiasan & Produk Turunannya',
    value: 4,
  },
  {
    label: 'Emas',
    category: 'Aksesori Perhiasan & Produk Turunannya',
    value: 4,
  },
  {
    label: 'Batu Giok',
    category: 'Aksesori Perhiasan & Produk Turunannya',
    value: 4,
  },
  {
    label: 'Mellite',
    category: 'Aksesori Perhiasan & Produk Turunannya',
    value: 4,
  },
  {
    label: 'Kristal Alami',
    category: 'Aksesori Perhiasan & Produk Turunannya',
    value: 4,
  },
  {
    label: 'Kristal Sintesis',
    category: 'Aksesori Perhiasan & Produk Turunannya',
    value: 4,
  },
  {
    label: 'Mutiara',
    category: 'Aksesori Perhiasan & Produk Turunannya',
    value: 4,
  },
  {
    label: 'Platina & Emas Karat',
    category: 'Aksesori Perhiasan & Produk Turunannya',
    value: 4,
  },
  {
    label: 'Batu delima, Safir & Zamrud',
    category: 'Aksesori Perhiasan & Produk Turunannya',
    value: 4,
  },
  {
    label: 'Batu Semimulia',
    category: 'Aksesori Perhiasan & Produk Turunannya',
    value: 4,
  },
  {
    label: 'Perak',
    category: 'Aksesori Perhiasan & Produk Turunannya',
    value: 4,
  },
  {
    label: 'Tas Jinjing',
    category: 'Koper & Tas',
    value: 6.5,
  },
  {
    label: 'Koper & Tas Travel',
    category: 'Koper & Tas',
    value: 6.5,
  },
  {
    label: 'Tas Pria',
    category: 'Koper & Tas',
    value: 6.5,
  },
  {
    label: 'Tas Wanita',
    category: 'Koper & Tas',
    value: 6.5,
  },
  {
    label: 'Bawahan Pria',
    category: 'Pakaian & Pakaian Dalam Pria',
    value: 6.5,
  },
  {
    label: 'Baju Tidur & Baju Santai Pria',
    category: 'Pakaian & Pakaian Dalam Pria',
    value: 6.5,
  },
  {
    label: 'Pakaian Khusus Pria',
    category: 'Pakaian & Pakaian Dalam Pria',
    value: 6.5,
  },
  {
    label: 'Setelan & Overall Pria',
    category: 'Pakaian & Pakaian Dalam Pria',
    value: 6.5,
  },
  {
    label: 'Atasan Pria',
    category: 'Pakaian & Pakaian Dalam Pria',
    value: 6.5,
  },
  {
    label: 'Pakaian Dalam Pria',
    category: 'Pakaian & Pakaian Dalam Pria',
    value: 6.5,
  },
  {
    label: 'Hijab',
    category: 'Busana Muslim',
    value: 6.5,
  },
  {
    label: 'Aksesoris Muslim',
    category: 'Busana Muslim',
    value: 6.5,
  },
  {
    label: 'Pakaian Olahraga Muslim',
    category: 'Busana Muslim',
    value: 6.5,
  },
  {
    label: 'Pakaian Muslim Anak-anak',
    category: 'Busana Muslim',
    value: 6.5,
  },
  {
    label: 'Pakaian Muslim Pria',
    category: 'Busana Muslim',
    value: 6.5,
  },
  {
    label: 'Outer',
    category: 'Busana Muslim',
    value: 6.5,
  },
  {
    label: 'Pakaian & Alat Ibadah',
    category: 'Busana Muslim',
    value: 6.5,
  },
  {
    label: 'Perlengkapan Umrah',
    category: 'Busana Muslim',
    value: 6.5,
  },
  {
    label: 'Pakaian Muslim Wanita',
    category: 'Busana Muslim',
    value: 6.5,
  },
  {
    label: 'Sepatu Pria',
    category: 'Sepatu',
    value: 6.5,
  },
  {
    label: 'Aksesoris Sepatu',
    category: 'Sepatu',
    value: 6.5,
  },
  {
    label: 'Sepatu Wanita',
    category: 'Sepatu',
    value: 6.5,
  },
  {
    label: 'Peralatan Olahraga Bola',
    category: 'Olahraga & Outdoor',
    value: 6.5,
  },
  {
    label: 'Peralatan Berkemah & Mendaki',
    category: 'Olahraga & Outdoor',
    value: 6.5,
  },
  {
    label: 'Suvenir Acara',
    category: 'Olahraga & Outdoor',
    value: 6.5,
  },
  {
    label: 'Toko Merchandise',
    category: 'Olahraga & Outdoor',
    value: 6.5,
  },
  {
    label: 'Peralatan Kebugaran',
    category: 'Olahraga & Outdoor',
    value: 6.5,
  },
  {
    label: 'Peralatan Bersantai & Rekreasi Luar Ruangan',
    category: 'Olahraga & Outdoor',
    value: 6.5,
  },
  {
    label: 'Pakaian Olahraga & Outdoor',
    category: 'Olahraga & Outdoor',
    value: 6.5,
  },
  {
    label: 'Aksesoris Olahraga & Outdoor',
    category: 'Olahraga & Outdoor',
    value: 6.5,
  },
  {
    label: 'Sepatu Olahraga',
    category: 'Olahraga & Outdoor',
    value: 6.5,
  },
  {
    label: 'Baju Renang, Baju Selancar & Baju Selam',
    category: 'Olahraga & Outdoor',
    value: 6.5,
  },
  {
    label: 'Peralatan Olahraga Air',
    category: 'Olahraga & Outdoor',
    value: 6.5,
  },
  {
    label: 'Peralatan Olahraga Musim Dingin',
    category: 'Olahraga & Outdoor',
    value: 6.5,
  },
  {
    label: 'Pakaian Dalam dan Stoking',
    category: 'Pakaian & Pakaian Dalam Wanita',
    value: 6.5,
  },
  {
    label: 'Bawahan Wanita',
    category: 'Pakaian & Pakaian Dalam Wanita',
    value: 6.5,
  },
  {
    label: 'Gaun Wanita',
    category: 'Pakaian & Pakaian Dalam Wanita',
    value: 6.5,
  },
  {
    label: 'Baju Tidur dan Baju Santai Wanita',
    category: 'Pakaian & Pakaian Dalam Wanita',
    value: 6.5,
  },
  {
    label: 'Pakaian Khusus Wanita',
    category: 'Pakaian & Pakaian Dalam Wanita',
    value: 6.5,
  },
  {
    label: 'Setelan & Overall Wanita',
    category: 'Pakaian & Pakaian Dalam Wanita',
    value: 6.5,
  },
  {
    label: 'Atasan Wanita',
    category: 'Pakaian & Pakaian Dalam Wanita',
    value: 6.5,
  },
  {
    label: 'Pakaian Dalam Wanita',
    category: 'Pakaian & Pakaian Dalam Wanita',
    value: 6.5,
  },
  {
    label: 'Buku Anak & Bayi',
    category: 'Buku, Majalah, & Audio',
    value: 6.5,
  },
  {
    label: 'Ekonomi & Manajemen',
    category: 'Buku, Majalah, & Audio',
    value: 6.5,
  },
  {
    label: 'BEdukasi & Sekolah',
    category: 'Buku, Majalah, & Audio',
    value: 6.5,
  },
  {
    label: 'Kemanusiaan & Ilmu Sosial',
    category: 'Buku, Majalah, & Audio',
    value: 6.5,
  },
  {
    label: 'Gaya Hidup & Hobi',
    category: 'Buku, Majalah, & Audio',
    value: 6.5,
  },
  {
    label: 'Sastra & Seni',
    category: 'Buku, Majalah, & Audio',
    value: 6.5,
  },
  {
    label: 'Majalah & Surat Kabar',
    category: 'Buku, Majalah, & Audio',
    value: 6.5,
  },
  {
    label: 'Sains & Teknologi',
    category: 'Buku, Majalah, & Audio',
    value: 6.5,
  },
  {
    label: 'Aksesori Komputer',
    category: 'Komputer & Peralatan Kantor',
    value: 5.5,
  },
  {
    label: 'Komponen Komputer',
    category: 'Komputer & Peralatan Kantor',
    value: 5.5,
  },
  {
    label: 'Penyimpanan Data & Software',
    category: 'Komputer & Peralatan Kantor',
    value: 4,
  },
  {
    label: 'Komponen Desktop & Laptop',
    category: 'Komputer & Peralatan Kantor',
    value: 4,
  },
  {
    label: 'Komponen Desktop, Laptop & Tablet',
    category: 'Komputer & Peralatan Kantor',
    value: 4,
  },
  {
    label: 'Komponen Jaringan',
    category: 'Komputer & Peralatan Kantor',
    value: 5.5,
  },
  {
    label: 'Peralatan Kantor',
    category: 'Komputer & Peralatan Kantor',
    value: 5.5,
  },
  {
    label: 'Alat Tulis & Perlengkapan Kantor',
    category: 'Komputer & Peralatan Kantor',
    value: 6,
  },
  {
    label: 'Alat Kebersihan',
    category: 'Peralatan Rumah Tangga',
    value: 5.5,
  },
  {
    label: 'Peralatan Komersial',
    category: 'Peralatan Rumah Tangga',
    value: 5.5,
  },
  {
    label: 'Perlengkapan Rumah Tangga',
    category: 'Peralatan Rumah Tangga',
    value: 4,
  },
  {
    label: 'Peralatan Dapur',
    category: 'Peralatan Rumah Tangga',
    value: 4,
  },
  {
    label: 'Televisi',
    category: 'Peralatan Rumah Tangga',
    value: 5.5,
  },
  {
    label: 'Suku Cadang & Aksesoris Peralatan Besar',
    category: 'Peralatan Rumah Tangga',
    value: 5.5,
  },
  {
    label: 'Oven, Kompor & Kompor',
    category: 'Peralatan Rumah Tangga',
    value: 4,
  },
  {
    label: 'Mesin Cuci & Pengering',
    category: 'Peralatan Rumah Tangga',
    value: 4,
  },
  {
    label: 'Pendingin Ruangan (AC)',
    category: 'Peralatan Rumah Tangga',
    value: 4,
  },
  {
    label: 'Kulkas & Freezer',
    category: 'Peralatan Rumah Tangga',
    value: 4,
  },
  {
    label: 'Range Hoods',
    category: 'Peralatan Rumah Tangga',
    value: 4,
  },
  {
    label: 'Pemanas Air',
    category: 'Peralatan Rumah Tangga',
    value: 5.5,
  },
  {
    label: 'Mesin Cuci Piring',
    category: 'Peralatan Rumah Tangga',
    value: 4,
  },
  {
    label: 'Perangkat Media Streaming',
    category: 'Peralatan Rumah Tangga',
    value: 5.5,
  },
  {
    label: 'Audio & Video',
    category: 'Audio & Video',
    value: 5.5,
  },
  {
    label: 'Kamera',
    category: 'Ponsel & Elektronik',
    value: 4,
  },
  {
    label: 'Aksesoris Kamera',
    category: 'Ponsel & Elektronik',
    value: 5.5,
  },
  {
    label: 'Perawatan Kamera',
    category: 'Ponsel & Elektronik',
    value: 6.5,
  },
  {
    label: 'Lensa Kamera',
    category: 'Ponsel & Elektronik',
    value: 5.5,
  },
  {
    label: 'DSLR',
    category: 'Ponsel & Elektronik',
    value: 4,
  },
  {
    label: 'Drone & Aksesoris',
    category: 'Ponsel & Elektronik',
    value: 4,
  },
  {
    label: 'Kamera Film',
    category: 'Ponsel & Elektronik',
    value: 6.5,
  },
  {
    label: 'Kamera Instan',
    category: 'Ponsel & Elektronik',
    value: 4,
  },
  {
    label: 'Kamera Mirrorless',
    category: 'Ponsel & Elektronik',
    value: 4,
  },
  {
    label: 'Point & Shoot Kamera',
    category: 'Ponsel & Elektronik',
    value: 4,
  },
  {
    label: 'Kamera & Sistem Keamanan',
    category: 'Ponsel & Elektronik',
    value: 5.5,
  },
  {
    label: 'Camcorder Video',
    category: 'Ponsel & Elektronik',
    value: 4,
  },
  {
    label: 'Perangkat Edukasi',
    category: 'Ponsel & Elektronik',
    value: 5.5,
  },
  {
    label: 'Game & Konsol',
    category: 'Ponsel & Elektronik',
    value: 5.5,
  },
  {
    label: 'Aksesoris Ponsel',
    category: 'Ponsel & Elektronik',
    value: 6.5,
  },
  {
    label: 'Ponsel & Tablet',
    category: 'Ponsel & Elektronik',
    value: 4,
  },
  {
    label: 'Perangkat Pintar & wearable',
    category: 'Ponsel & Elektronik',
    value: 6.5,
  },
  {
    label: 'Stylus',
    category: 'Ponsel & Elektronik',
    value: 6.5,
  },
  {
    label: 'Tablet Keyboard',
    category: 'Ponsel & Elektronik',
    value: 5.5,
  },
  {
    label: 'Cover & Casing Tablet',
    category: 'Ponsel & Elektronik',
    value: 6.5,
  },
  {
    label: 'Dudukan & Alas Tablet',
    category: 'Ponsel & Elektronik',
    value: 5.5,
  },
  {
    label: 'Pelindung Layar Tablet',
    category: 'Ponsel & Elektronik',
    value: 6.5,
  },
  {
    label: 'Tas Tablet',
    category: 'Ponsel & Elektronik',
    value: 6.5,
  },
  {
    label: 'Pengisi Daya & Adaptor Tablet',
    category: 'Ponsel & Elektronik',
    value: 6.5,
  },
  {
    label: 'Bagian Tablet',
    category: 'Ponsel & Elektronik',
    value: 6.5,
  },
  {
    label: 'Aksesoris Universal',
    category: 'Ponsel & Elektronik',
    value: 6,
  },
  {
    label: 'Video Game/Aksesori/Game/Permainan Strategi',
    category: 'Ponsel & Elektronik',
    value: 5.5,
  },
  {
    label: 'Telekomunikasi',
    category: 'Produk Virtual',
    value: 1,
  },
  {
    label: 'Perawatan & Kesehatan Bayi',
    category: 'Bayi & Ibu Hamil',
    value: 6.5,
  },
  {
    label: 'Pakaian & Sepatu Bayi',
    category: 'Bayi & Ibu Hamil',
    value: 6.5,
  },
  {
    label: 'Aksesoris Fashion Bayi',
    category: 'Bayi & Ibu Hamil',
    value: 6.5,
  },
  {
    label: 'Furnitur Bayi',
    category: 'Bayi & Ibu Hamil',
    value: 6.5,
  },
  {
    label: 'Produk Bayi',
    category: 'Bayi & Ibu Hamil',
    value: 6.5,
  },
  {
    label: 'Produk Keamanan Bayi',
    category: 'Bayi & Ibu Hamil',
    value: 6.5,
  },
  {
    label: 'Mainan Bayi',
    category: 'Bayi & Ibu Hamil',
    value: 6.5,
  },
  {
    label: 'Perlengkapan Bayi untuk Bepergian',
    category: 'Bayi & Ibu Hamil',
    value: 6.5,
  },
  {
    label: 'Susu Formula & Makanan Bayi',
    category: 'Bayi & Ibu Hamil',
    value: 4,
  },
  {
    label: 'Perlengkapan Ibu Hamil',
    category: 'Bayi & Ibu Hamil',
    value: 6,
  },
  {
    label: 'Perlengkapan Menyusui & Alat Makan Bayi',
    category: 'Bayi & Ibu Hamil',
    value: 6,
  },
  {
    label: 'Perlengkapan Mandi & Perawatan Tubuh',
    category: 'Kecantikan & Perawatan Pribadi',
    value: 6,
  },
  {
    label: 'Perawatan Mata & Telinga',
    category: 'Kecantikan & Perawatan Pribadi',
    value: 6.5,
  },
  {
    label: 'Perawatan Kewanitaan',
    category: 'Kecantikan & Perawatan Pribadi',
    value: 6.5,
  },
  {
    label: 'Perawatan & Penataan Rambut',
    category: 'Kecantikan & Perawatan Pribadi',
    value: 6.5,
  },
  {
    label: 'Perawatan Tangan, Kaki & Kuku',
    category: 'Kecantikan & Perawatan Pribadi',
    value: 6.5,
  },
  {
    label: 'Makeup',
    category: 'Kecantikan & Perawatan Pribadi',
    value: 6.5,
  },
  {
    label: 'Perawatan Pria',
    category: 'Kecantikan & Perawatan Pribadi',
    value: 6.5,
  },
  {
    label: 'Perawatan Hidung & Mulut',
    category: 'Kecantikan & Perawatan Pribadi',
    value: 6.5,
  },
  {
    label: 'Parfum',
    category: 'Kecantikan & Perawatan Pribadi',
    value: 6.5,
  },
  {
    label: 'Perawatan Peralatan Mandi',
    category: 'Kecantikan & Perawatan Pribadi',
    value: 6.5,
  },
  {
    label: 'Perawatan Kulit',
    category: 'Kecantikan & Perawatan Pribadi',
    value: 6.5,
  },
  {
    label: 'Perawatan Pribadi Khusus',
    category: 'Kecantikan & Perawatan Pribadi',
    value: 5.5,
  },
  {
    label: 'Makup & Parfum',
    category: 'Kecantikan & Perawatan Pribadi',
    value: 6.5,
  },
  {
    label: 'Kecantikan & Perawatan Kulit',
    category: 'Kecantikan & Perawatan Pribadi',
    value: 6.5,
  },
  {
    label: 'Alat Kecantikan & Perawatan Pribadi',
    category: 'Kecantikan & Perawatan Pribadi',
    value: 6.5,
  },
  {
    label: 'Perawatan Rambut',
    category: 'Kecantikan & Perawatan Pribadi',
    value: 6.5,
  },
  {
    label: 'Perawatan Pribadi',
    category: 'Kecantikan & Perawatan Pribadi',
    value: 5.5,
  },
  {
    label: 'Kue',
    category: 'Makanan & Minuman',
    value: 5,
  },
  {
    label: 'Bumbu & Saus',
    category: 'Makanan & Minuman',
    value: 4,
  },
  {
    label: 'Minuman',
    category: 'Makanan & Minuman',
    value: 5.5,
  },
  {
    label: 'Makanan Segar & Beku',
    category: 'Makanan & Minuman',
    value: 4,
  },
  {
    label: 'Makanan Instan',
    category: 'Makanan & Minuman',
    value: 6.5,
  },
  {
    label: 'Susu & Produk Susu',
    category: 'Makanan & Minuman',
    value: 5.5,
  },
  {
    label: 'Makanan Lain',
    category: 'Makanan & Minuman',
    value: 6.5,
  },
  {
    label: 'Kacang Camilan',
    category: 'Makanan & Minuman',
    value: 6.5,
  },
  {
    label: 'Makanan Ringan',
    category: 'Makanan & Minuman',
    value: 6,
  },
  {
    label: 'Bahan Pokok & Perlengkapan Memasak',
    category: 'Makanan & Minuman',
    value: 4,
  },
  {
    label: 'Pengobatan & Perawatan Alternatif',
    category: 'Kesehatan',
    value: 5.5,
  },
  {
    label: 'Suplemen Makanan',
    category: 'Kesehatan',
    value: 5.5,
  },
  {
    label: 'Suplai Medis',
    category: 'Kesehatan',
    value: 5.5,
  },
  {
    label: 'Pengobatan & Perawatan OTC',
    category: 'Kesehatan',
    value: 5.5,
  },
  {
    label: 'Pakaian Anak Laki-Laki',
    category: 'Pakaian Anak',
    value: 6.5,
  },
  {
    label: 'Alas Kaki Anak Laki-Laki',
    category: 'Pakaian Anak',
    value: 6.5,
  },
  {
    label: 'Pakaian Anak Perempuan',
    category: 'Pakaian Anak',
    value: 6.5,
  },
  {
    label: 'Alas Kaki Anak Perempuan',
    category: 'Pakaian Anak',
    value: 6.5,
  },
  {
    label: 'Aksesoris Fashion Anak',
    category: 'Pakaian Anak',
    value: 6,
  },
  {
    label: 'Minuman',
    category: 'Minuman Keras dan Produk Minuman',
    value: 5.5,
  },
  {
    label: 'Teh',
    category: 'Minuman Keras dan Produk Minuman',
    value: 5.5,
  },
  {
    label: 'Suku Cadang Pengganti Otomatis',
    category: 'Mobil & Sepeda Motor',
    value: 5.5,
  },
  {
    label: 'Elektronik Mobil',
    category: 'Mobil & Sepeda Motor',
    value: 6.5,
  },
  {
    label: 'Aksesoris Eksterior Mobil',
    category: 'Mobil & Sepeda Motor',
    value: 6.5,
  },
  {
    label: 'Aksesoris Interior Mobil',
    category: 'Mobil & Sepeda Motor',
    value: 6.5,
  },
  {
    label: 'Lampu Mobil',
    category: 'Mobil & Sepeda Motor',
    value: 5.5,
  },
  {
    label: 'Alat Perbaikan Mobil',
    category: 'Mobil & Sepeda Motor',
    value: 6.5,
  },
  {
    label: 'Pencucian & Perawatan Mobil',
    category: 'Mobil & Sepeda Motor',
    value: 6.5,
  },
  {
    label: 'Aksesoris Sepeda Motor',
    category: 'Mobil & Sepeda Motor',
    value: 6.5,
  },
  {
    label: 'Suku Cadang Sepeda Motor',
    category: 'Mobil & Sepeda Motor',
    value: 5.5,
  },
  {
    label: 'Koleksi Budaya Kontemporer',
    category: 'Barang Koleksi',
    value: 6.5,
  },
  {
    label: 'Hiburan',
    category: 'Barang Koleksi',
    value: 5.5,
  },
  {
    label: 'Koleksi Olahraga',
    category: 'Barang Koleksi',
    value: 6.5,
  },
  {
    label: 'Kartu Perdagangan & Aksesoris',
    category: 'Barang Koleksi',
    value: 5.5,
  },
  {
    label: 'Perabotan Anak',
    category: 'Furnitur',
    value: 6.5,
  },
  {
    label: 'Perabotan Komersial',
    category: 'Furnitur',
    value: 6.5,
  },
  {
    label: 'Bagian Furnitur',
    category: 'Furnitur',
    value: 6.5,
  },
  {
    label: 'Perabotan Dalam Ruangan',
    category: 'Furnitur',
    value: 6,
  },
  {
    label: 'Perabotan Luar Ruangan',
    category: 'Furnitur',
    value: 6,
  },
  {
    label: 'Perlengkapan Kamar Mandi',
    category: 'Dekorasi Rumah',
    value: 6.5,
  },
  {
    label: 'Perlengkapan Bangunan',
    category: 'Dekorasi Rumah',
    value: 6.5,
  },
  {
    label: 'Peralatan & Perlengkapan Listrik',
    category: 'Dekorasi Rumah',
    value: 6.5,
  },
  {
    label: 'Perlengkapan Tanam',
    category: 'Dekorasi Rumah',
    value: 6.5,
  },
  {
    label: 'Perlengkapan Dapur',
    category: 'Dekorasi Rumah',
    value: 6.5,
  },
  {
    label: 'Lampu & Pencahayaan',
    category: 'Dekorasi Rumah',
    value: 6.5,
  },
  {
    label: 'Keamanan & Keselamatan',
    category: 'Dekorasi Rumah',
    value: 6.5,
  },
  {
    label: 'Sistem Rumah Pintar (Smart-Home)',
    category: 'Dekorasi Rumah',
    value: 6.5,
  },
  {
    label: 'Tenaga Surya & Angin',
    category: 'Dekorasi Rumah',
    value: 6.5,
  },
  {
    label: 'Perlengkapan Kamar Mandi',
    category: 'Perlengkapan Rumah',
    value: 6.5,
  },
  {
    label: 'Perlengkapan Rumah Tangga Sehari-hari',
    category: 'Perlengkapan Rumah',
    value: 6.5,
  },
  {
    label: 'Perlengkapan Perayaan & Pesta',
    category: 'Perlengkapan Rumah',
    value: 6.5,
  },
  {
    label: 'Aksesoris Rumah',
    category: 'Perlengkapan Rumah',
    value: 6.5,
  },
  {
    label: 'Perlengkapan Perawatan di Rumah',
    category: 'Perlengkapan Rumah',
    value: 6.5,
  },
  {
    label: 'Dekorasi Rumah',
    category: 'Perlengkapan Rumah',
    value: 6.5,
  },
  {
    label: 'Penyelenggara Rumah',
    category: 'Perlengkapan Rumah',
    value: 6.5,
  },
  {
    label: 'Pembersih Rumah Tangga',
    category: 'Perlengkapan Rumah',
    value: 6.5,
  },
  {
    label: 'Alat & Aksesoris',
    category: 'Perlengkapan Rumah',
    value: 6.5,
  },
  {
    label: 'Perlengkapan Rumah Lainnya',
    category: 'Perlengkapan Rumah',
    value: 6.5,
  },
  {
    label: 'Lain-lain',
    category: 'Perlengkapan Rumah',
    value: 6.5,
  },
  {
    label: 'Peralatan Memanggang',
    category: 'Perlengkapan Dapur',
    value: 6.5,
  },
  {
    label: 'Peralatan Bar & Anggur',
    category: 'Perlengkapan Dapur',
    value: 6.5,
  },
  {
    label: 'Panggang',
    category: 'Perlengkapan Dapur',
    value: 4,
  },
  {
    label: 'Peralatan Masak',
    category: 'Perlengkapan Dapur',
    value: 6.5,
  },
  {
    label: 'Peralatan Makan',
    category: 'Perlengkapan Dapur',
    value: 6.5,
  },
  {
    label: 'Perlengkapan Minum',
    category: 'Perlengkapan Dapur',
    value: 6.5,
  },
  {
    label: 'Pisau Dapur',
    category: 'Perlengkapan Dapur',
    value: 6.5,
  },
  {
    label: 'Peralatan & Gadget Dapur',
    category: 'Perlengkapan Dapur',
    value: 6.5,
  },
  {
    label: 'Peralatan Teh & Kopi',
    category: 'Perlengkapan Dapur',
    value: 6.5,
  },
  {
    label: 'Persediaan Burung',
    category: 'Perlengkapan Hewan Peliharaan',
    value: 5.5,
  },
  {
    label: 'Aksesoris Anjing & Kucing',
    category: 'Perlengkapan Hewan Peliharaan',
    value: 5.5,
  },
  {
    label: 'Pakaian Anjing & Kucing',
    category: 'Perlengkapan Hewan Peliharaan',
    value: 5.5,
  },
  {
    label: 'Makanan Anjing & Kucing',
    category: 'Perlengkapan Hewan Peliharaan',
    value: 5.5,
  },
  {
    label: 'Furnitur Anjing & Kucing',
    category: 'Perlengkapan Hewan Peliharaan',
    value: 5.5,
  },
  {
    label: 'Perawatan Anjing & Kucing',
    category: 'Perlengkapan Hewan Peliharaan',
    value: 5.5,
  },
  {
    label: 'Perawatan Kesehatan Anjing & Kucing',
    category: 'Perlengkapan Hewan Peliharaan',
    value: 5.5,
  },
  {
    label: 'Kotoran Anjing & Kucing',
    category: 'Perlengkapan Hewan Peliharaan',
    value: 5.5,
  },
  {
    label: 'Persediaan Hewan Ternak & Unggas',
    category: 'Perlengkapan Hewan Peliharaan',
    value: 5.5,
  },
  {
    label: 'Persediaan Ikan & Perairan',
    category: 'Perlengkapan Hewan Peliharaan',
    value: 5.5,
  },
  {
    label: 'Persediaan Reptil & Amfibi',
    category: 'Perlengkapan Hewan Peliharaan',
    value: 5.5,
  },
  {
    label: 'Persediaan Hewan Kecil',
    category: 'Perlengkapan Hewan Peliharaan',
    value: 5.5,
  },
  {
    label: 'Seperai',
    category: 'Tekstil & Produk dari Kain',
    value: 6.5,
  },
  {
    label: 'Kain & Perlengkapan Jahit',
    category: 'Tekstil & Produk dari Kain',
    value: 5,
  },
  {
    label: 'Tekstil Rumah Tangga',
    category: 'Tekstil & Produk dari Kain',
    value: 6.5,
  },
  {
    label: 'Peralatan kebun',
    category: 'Alat & Perkakas',
    value: 6.5,
  },
  {
    label: 'Perkakas',
    category: 'Alat & Perkakas',
    value: 6.5,
  },
  {
    label: 'Perangkat Keras',
    category: 'Alat & Perkakas',
    value: 6.5,
  },
  {
    label: 'Alat Ukur',
    category: 'Alat & Perkakas',
    value: 6.5,
  },
  {
    label: 'Perkakas Listrik',
    category: 'Alat & Perkakas',
    value: 6.5,
  },
  {
    label: 'Pompa & Plumbing',
    category: 'Alat & Perkakas',
    value: 6.5,
  },
  {
    label: 'Peralatan Penyolderan',
    category: 'Alat & Perkakas',
    value: 6.5,
  },
  {
    label: 'Penyelenggara Alat',
    category: 'Alat & Perkakas',
    value: 6.5,
  },
  {
    label: 'Mainan Klasik & Baru',
    category: 'Mainan & Hobi',
    value: 5.5,
  },
  {
    label: 'Buatan Sendiri',
    category: 'Mainan & Hobi',
    value: 6.5,
  },
  {
    label: 'Boneka & Boneka Mainan',
    category: 'Mainan & Hobi',
    value: 6.5,
  },
  {
    label: 'Mainan Pendidikan',
    category: 'Mainan & Hobi',
    value: 6,
  },
  {
    label: 'Mainan Listrik & Remote Control',
    category: 'Mainan & Hobi',
    value: 5.5,
  },
  {
    label: 'Permainan Teka-Teki',
    category: 'Mainan & Hobi',
    value: 6,
  },
  {
    label: 'Alat & Aksesoris Musik',
    category: 'Mainan & Hobi',
    value: 5.5,
  },
  {
    label: 'Model Plastik/Anime/Produk Terkait Lainnya/Cosplay/Permainan Papan',
    category: 'Mainan & Hobi',
    value: 6.5,
  },
  {
    label: 'Olahraga & Permainan Luar Ruangan',
    category: 'Mainan & Hobi',
    value: 5.5,
  },
];
